name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarScanner for .NET
        shell: powershell
        run: |
          dotnet tool update --global dotnet-sonarscanner

      - name: Install Coverlet Console
        shell: powershell
        run: |
          dotnet tool install --global coverlet.console
          dotnet add test/MyTestProject.csproj package coverlet.collector

      - name: Start SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet-sonarscanner begin /k:"tungnk123_DotNet-Sonar-Lens" /o:"tungnk123" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="TestResults/coverage.opencover.xml"

      - name: Restore NuGet Packages 
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Run Tests with Coverage
        run: |
          dotnet test test/MyTestProject.csproj --collect:"XPlat Code Coverage" --results-directory TestResults/
          reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:TestResults/CoverageReport -reporttypes:SonarQube

      - name: Complete SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
